# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.
name = "tardis"
target = "javascript"
version = "0.2.0"

gleam = ">= 1.4.0"

description = "Time traveller debugger, tailor-made for Lustre"
internal_modules = ["tardis/internals", "tardis/internals/*"]
licences = ["MIT"]
links = [{title = "Sponsor", href = "https://github.com/sponsors/ghivert"}]
repository = {type = "github", user = "ghivert", repo = "tardis"}

[dependencies]
gleam_stdlib = ">= 0.40.0 and < 1.0.0"
lustre = ">= 4.3.1 and < 5.0.0"
plinth = ">= 0.4.14 and < 1.0.0"
sketch = ">= 3.1.0 and < 4.0.0"
sketch_lustre = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.1.2 and < 2.0.0"
